/**
 * Mapped 1:1 from `fromWebCss/pages/LoginPage.css` +
 * `fromWebCss/components/login/LoginMobileExtras.css` (mobile ≤860px).
 */
import {StyleSheet} from 'react-native';

export const WEB = {
  background: '#F5F7FA',
  card: '#FFFFFF',
  text: '#1A202C',
  textSecondary: '#718096',
  primary: '#34C759',
  border: '#E2E8F0',
  error: '#FF3B30',
  navyBand: '#0F2F4F',
  navyMix: '#103843',
  otpIconBg: '#E8F1F8',
  otpIcon: '#2B6CB0',
  pinIconBg: '#E8F8EE',
  trustInfo: '#E8F1F8',
  trustInfoText: '#1A365D',
  primaryTint: 'rgba(52, 199, 89, 0.16)',
  primaryTint6: 'rgba(52, 199, 89, 0.06)',
  primaryTint8: 'rgba(52, 199, 89, 0.08)',
  primaryTint12: 'rgba(52, 199, 89, 0.12)',
  primaryTint14: 'rgba(52, 199, 89, 0.14)',
  primaryTint22: 'rgba(52, 199, 89, 0.22)',
  primaryTint28: 'rgba(52, 199, 89, 0.28)',
  borderMix: 'rgba(226, 232, 240, 0.55)',
  doneDot: '#2E9A4F',
} as const;

export const loginFromWeb = StyleSheet.create({
  layout: {
    flex: 1,
    backgroundColor: WEB.background,
  },
  navyBand: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '16%',
    backgroundColor: WEB.navyBand,
    pointerEvents: 'none',
  },
  stage: {
    flex: 1,
    paddingHorizontal: 12,
  },
  authStack: {
    flex: 1,
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F3FCF5',
    borderRadius: 20,
    paddingTop: 14,
    paddingHorizontal: 14,
    paddingBottom: 8,
    shadowColor: '#1E3C5A',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 2,
  },
  cardScroll: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  cardTop: {
    gap: 10,
    marginBottom: 4,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    minHeight: 36,
  },
  toolbarSpacer: {
    flex: 1,
    minWidth: 0,
  },
  backToolbar: {
    alignSelf: 'center',
    minHeight: 44,
    justifyContent: 'center',
    paddingVertical: 8,
    paddingRight: 8,
    margin: 0,
  },
  backText: {
    color: WEB.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  lang: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: WEB.border,
    backgroundColor: '#FAFBFC',
  },
  langBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
  },
  langBtnActive: {
    backgroundColor: WEB.primaryTint,
  },
  langBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: WEB.textSecondary,
  },
  langBtnTextActive: {
    color: WEB.primary,
    fontWeight: '700',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 2,
    marginBottom: 0,
  },
  logo: {
    width: 68,
    height: 68,
    borderRadius: 12,
  },
  brandCopy: {
    flexShrink: 1,
    minWidth: 0,
  },
  brandName: {
    margin: 0,
    fontSize: 18,
    fontWeight: '700',
    color: WEB.text,
    lineHeight: 22,
  },
  brandTag: {
    marginTop: 2,
    fontSize: 12,
    color: WEB.textSecondary,
  },
  cardBody: {
    flexDirection: 'column',
    gap: 8,
    flexGrow: 1,
  },
  stepHeader: {
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 6,
  },
  stepTitle: {
    marginBottom: 2,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: -0.34,
    color: WEB.text,
    lineHeight: 22,
    textAlign: 'center',
  },
  stepSub: {
    fontSize: 12,
    lineHeight: 17,
    color: WEB.textSecondary,
    paddingHorizontal: 4,
    textAlign: 'center',
  },
  form: {
    flexDirection: 'column',
    gap: 8,
    marginBottom: 0,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 2,
    color: WEB.textSecondary,
  },
  primaryBtn: {
    minHeight: 48,
  },
  fieldError: {
    marginTop: -4,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    color: WEB.error,
    textAlign: 'center',
  },
  customerOnly: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 4,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(52, 199, 89, 0.28)',
    backgroundColor: WEB.primaryTint6,
  },
  customerOnlyTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
    color: WEB.text,
  },
  customerOnlyBody: {
    fontSize: 13,
    lineHeight: 19,
    color: WEB.textSecondary,
  },
  readonlyPhone: {
    flexDirection: 'column',
    gap: 2,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 0,
    borderRadius: 14,
    backgroundColor: '#F1F4F8',
    borderWidth: 1,
    borderColor: WEB.border,
  },
  readonlyPhoneLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: WEB.textSecondary,
  },
  readonlyPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  readonlyPhoneValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.32,
    color: WEB.text,
  },
  editMobileBtn: {
    minHeight: 40,
    minWidth: 44,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editMobileText: {
    fontSize: 14,
    fontWeight: '700',
    color: WEB.primary,
  },
  pinFieldBlock: {
    flexDirection: 'column',
    gap: 6,
  },
  linkRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 4,
    marginTop: 0,
  },
  textLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  textLinkLabel: {
    color: WEB.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  textLinkMuted: {
    color: WEB.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  textLinkCenter: {
    justifyContent: 'center',
    width: '100%',
  },
  stepIcon: {
    width: 56,
    height: 56,
    marginTop: 0,
    marginBottom: 4,
    alignSelf: 'center',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepIconOtp: {
    backgroundColor: WEB.otpIconBg,
  },
  stepIconPin: {
    backgroundColor: WEB.pinIconBg,
  },
  otpInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: WEB.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 52,
    backgroundColor: WEB.card,
  },
  otpField: {
    flex: 1,
    marginLeft: 8,
    fontSize: 16,
    letterSpacing: 4,
    color: WEB.text,
    paddingVertical: 0,
  },
  pinReveal: {
    borderWidth: 2,
    borderColor: WEB.primary,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: WEB.card,
  },
  pinValue: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 8,
    marginTop: 8,
    color: WEB.text,
  },
  trustBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: 6,
    marginTop: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: WEB.border,
    backgroundColor: '#F7F8FA',
  },
  trustBadgeText: {
    color: WEB.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  extras: {
    width: '100%',
    marginTop: 8,
    gap: 8,
    flexGrow: 1,
  },
  utilRow: {
    flexDirection: 'row',
    marginTop: 0,
    gap: 2,
  },
  utilBtn: {
    flex: 1,
    minHeight: 44,
    paddingVertical: 2,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    borderRadius: 10,
  },
  utilBtnText: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 12,
    textAlign: 'center',
    color: WEB.textSecondary,
  },
  extrasBottom: {
    marginTop: 'auto',
    alignItems: 'center',
    gap: 10,
    paddingTop: 8,
    paddingBottom: 4,
  },
  partnerLink: {
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    gap: 2,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  partnerLinkTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: WEB.textSecondary,
    lineHeight: 16,
  },
  partnerLinkCta: {
    fontSize: 12,
    fontWeight: '700',
    color: WEB.primary,
    lineHeight: 16,
  },
  extrasFoot: {
    alignItems: 'center',
    gap: 2,
    paddingTop: 4,
    paddingHorizontal: 4,
  },
  extrasTrust: {
    fontSize: 11,
    fontWeight: '600',
    color: WEB.textSecondary,
  },
  extrasTerms: {
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 14,
    color: WEB.textSecondary,
  },
  extrasTermsLink: {
    color: WEB.primary,
    fontWeight: '700',
  },
  boot: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: WEB.background,
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 12,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: WEB.border,
  },
  orText: {
    fontSize: 13,
    fontWeight: '600',
    color: WEB.textSecondary,
  },
  guestBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
    minHeight: 44,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: WEB.border,
    borderRadius: 16,
    backgroundColor: WEB.card,
  },
  guestBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: WEB.text,
  },
  guestHint: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 19,
    color: WEB.textSecondary,
    paddingHorizontal: 4,
  },
  primaryFill: {
    minHeight: 48,
    borderRadius: 10,
    backgroundColor: WEB.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryFillText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  bioPrimary: {
    marginTop: 4,
  },
  bioPrimaryInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
});
